version: "3.9"

services:
  mongo:
    image: mongo:latest
    networks: 
      - dev
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27019:27017"

  nest-app:
    build: .
    networks: 
      - dev
    restart: unless-stopped
    ports:
      - "3000:3000"  # Replace with your desired port
    depends_on:
      - mongo
    volumes:
      - .:/app
networks:
  dev:
    driver: bridge